---
- name: reload udev rules
  become: true
  ansible.builtin.shell: >-
    udevadm control --reload-rules
    udevadm trigger

- name: reload service
  become: true
  ansible.builtin.systemd:
    name: r8153-ethernet-adapter-fix
    state: restarted
    enabled: true
    daemon_reload: true

- name: reboot
  become: true
  ansible.builtin.reboot:
