# This play will set up the compute nodes after having their filesystems
# initialized in the =setup-head-node.yml= play.
---

- name: Configure compute nodes
  hosts: compute_nodes
  gather_facts: false

  pre_tasks:
    - ansible.builtin.setup:
        gather_subset:
          - "network"

  tasks:
    - name: Disable unneccessary system services.
      become: true
      ansible.builtin.systemd_service:
        name: "{{ item }}"
        enabled: false
        masked: true
        force: true
      loop:
        - resize2fs_once
        - sshswitch

    - name: Remove dphys-swapfile program.
      become: true
      ansible.builtin.apt:
        name: dphys-swapfile
        state: absent

    - name: Create scratch disk
      become: true
      ansible.builtin.file:
        path: /scratch
        state: directory
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"

    - name: Configure NFS entry.
      become: true
      ansible.posix.mount:
        path: /scratch
        src: "{{ cluster_network_portion }}.1:/mnt/usb/scratch"
        fstype: nfs
        opts: defaults
        dump: 0
        passno: 0
        state: mounted
