---
- name: Setup Head Node
  hosts: head_node

  tasks:
    - name: Set static IP on Home LAN.
      become: true
      community.general.nmcli:
        type: ethernet
        ifname: eth1
        conn_name: Home LAN
        ip4: 10.13.37.101/24
        gw4: 10.13.37.1
        dns4: [ "8.8.8.8", "8.8.4.4" ]
        autoconnect: true
        state: present

    - name: Allocate address space for internal cluster.
      become: true
      community.general.nmcli:
        type: ethernet
        ifname: eth0
        conn_name: Cluster Connection
        ip4: "{{ cluster_network_portion }}.1/24"
        method4: manual
        state: present

    - name: Copy default sshd_config file.
      become: true
      ansible.builtin.copy:
        dest: "/etc/ssh/sshd_config"
        src: head_node_sshd_config
        owner: root
        group: root
        mode: "644"

    - name: Set up DHCP server.
      ansible.builtin.include_role:
        name: dhcp-server

    - name: Apply R8153 ethernet adapter workaround.
      ansible.builtin.include_role:
        name: rtl8153-workaround

    - name: Set up shared filesystem.
      ansible.builtin.include_role:
        name: filesystem
    
    - name: Set up TFTP service on filesystem.
      ansible.builtin.include_role:
        name: tftp-server

    - name: Enroll compute nodes to filesystem.
      ansible.builtin.include_role:
        name: enroll-compute-nodes
